### PR TITLE
Update agent_diag.go

### PR DESCRIPTION
**Pull request by pj7810**
if network error, resp will be nil, the call: resp.sourceAddr will crush

### CODE REVIEW

**Comment by brett19** [comment]
*poke*

**Comment by chvck** [comment]
Hi @pj7810 thanks for your pull request. Have you signed up to our Gerrit review system and signed the CLA?

**Comment by pj7810** [comment]
yes, I had signed

**Comment by chvck** [comment]
Hi @pj7810 not entirely sure what's happened here but somehow we seem to have loads of unintended changes. It might be easiest if you close this PR and recreate it with only your original commit.

**Comment by pj7810** [comment]
> Hi @pj7810 not entirely sure what's happened here but somehow we seem to have loads of unintended changes. It might be easiest if you close this PR and recreate it with only your original commit.

Some conflicts need to resolve, I use git rebase to merge it...
Thanks for your advice, I will close this PR and recreate it.

**Pull request closed without merging**
