### PR TITLE
feat: replace  golang/snappy to klauspost/compress/snappy for faster and better performance

### PR DESCRIPTION
**Pull request by Abdulsametileri**
Hello, we use `couchbase/gocb/v2` in many of our projects. Unsurprisingly, we are indirectly using this package 😄 . 

Lately, when we monitor a few of our applications running under load, we saw `snappy.Decode` and `snappy.Encode`  function has lots of heap allocation. 

image
image
image
image

When we look at the [golang/snappy](https://github.com/golang/snappy/) library, it seems not actively maintained project. 
Then when we look at the alternatives to this package, we found https://github.com/klauspost/compress/tree/master/snappy

[Based on benchmarks and comparisons](https://github.com/klauspost/compress/tree/master/s2#s2-compression) this package is better than golang/snappy.

### CODE REVIEW

**Comment by chvck** [comment]
Hi @Abdulsametileri this is great, thanks. It'll take me a bit of time to verify that the new library does perform as we expect as a part of the SDK (although from the links that you've provided I don't think there will be any issues).

In the meantime, have you signed our CLA? Instructions can be found at https://github.com/couchbase/couchbase-jvm-clients/blob/master/CONTRIBUTING.md#pull-requests. Once you've signed the CLA I'll manually move your PR over to our gerrit review system (we can only accept PRs via that system unfortunately).

**Comment by Abdulsametileri** [comment]
Thank you for your response! I have signed the agreement, could you please check for me?

**Comment by chvck** [comment]
Hi @Abdulsametileri I can confirm that you're registered as having signed the CLA. I'll move over the PR and verify the change does what we expect at the beginning of next week.

**Comment by chvck** [comment]
I've moved the commit over to gerrit at https://review.couchbase.org/c/gocbcore/+/196262 and will do some work to try to verify that the new library uses less resources.

**Comment by Abdulsametileri** [comment]
@chvck, it seems the cause of more CPU usage instead of memory, you didn't accept this PR. If so we can close it :)

**Comment by chvck** [comment]
Hi @Abdulsametileri I'd like to do some more investigation into this first, I've just not had a chance to do so yet.

**Comment by chvck** [comment]
Hi @Abdulsametileri unfortunately I think so yes. I don't think that we can make the change as it changes the tradeoff to be increase CPU usage rather than memory. If we had a mechanism to allow users to specify the compression algorithm then I think that would be a good approach, however no SDKs support doing this and it's not functionality that we want to support at the moment. I'll ensure it gets considered when we do the next SDK round of dotmajors.

(I can't close this PS so I'll have to find someone else who can.)

**Comment by Abdulsametileri** [comment]
I did, thanks <3

**Pull request closed without merging**
